name: Build and Run Docker

on:
  push:
    branches:
      - master


jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Clone le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build \
            --build-arg NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }} \
            --build-arg HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }} \
            --build-arg MISTRAL_TOKEN=${{ secrets.MISTRAL_TOKEN }} \
            -t lina:latest .

      # Étape 3 : Tester l'image en local (optionnel)
      # - name: Run Docker container for testing
      #   run: |
      #     docker run --device /dev/snd -e VIDEO_SOURCE="0" lina:latest


      # Étape 4 : (Optionnel) Publier l'image vers Docker Hub ou GitHub Container Registry
      - name: Push Docker image to Docker Hub
        run: |
          docker tag lina:latest lelouch0909/lina:latest
          docker push lelouch0909/lina:latest
