name: LINA DOCKER IMAGE BUILD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          docker build \
            --build-arg NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }} \
            --build-arg HUGGINGFACEHUB_API_TOKEN=${{ secrets.HUGGINGFACEHUB_API_TOKEN }} \
            --build-arg MISTRAL_TOKEN=${{ secrets.MISTRAL_TOKEN }} \
            -t mydockerhubuser/my-python-app:latest .
          
          docker push mydockerhubuser/my-python-app:latest

      - name: Run Container
        run: |
          docker run -d \
            --name myapp \
            -p 5000:5000 \
            -e NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }} \
            -e HUGGINGFACEHUB_API_TOKEN=${{ secrets.HUGGINGFACEHUB_API_TOKEN }} \
            -e MISTRAL_TOKEN=${{ secrets.MISTRAL_TOKEN }} \
            mydockerhubuser/my-python-app:latest