name: Build and Run Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Clone le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build \
            --build-arg NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }} \
            --build-arg HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }} \
            --build-arg MISTRAL_TOKEN=${{ secrets.MISTRAL_TOKEN }} \
            -t my-python-app:latest .

      # Étape 3 : Tester l'image en local (optionnel)
      - name: Run Docker container for testing
        run: |
          docker run my-python-app:latest

      # Étape 4 : (Optionnel) Publier l'image vers Docker Hub ou GitHub Container Registry
      - name: Push Docker image to Docker Hub
        if: ${{ github.event_name == 'push' }}
        run: |
          docker tag my-python-app:latest mydockerhubuser/my-python-app:latest
          docker push mydockerhubuser/my-python-app:latest
